export const SQLITE_ROOT = "read-sqlite"

export const QUERY_LONGEST_QUERIES = "longestavgqueries"
export const QUERY_ALL_TIMESTAMPS = "allqueriestimes"
export const QUERY_COUNT = "querycount"
export const QUERY_PERCENTILE = "querypercentile"
export const QUERY_GET_QUERY_TEXT = "getquerytext"
export const QUERY_QUERY_COUNT_BY_SERVER = "getquerycountbyserver"
export const QUERY_TIME_QUERY_COUNT = "timequerycount"
export const QUERY_GET_PLANNING_PCT = "planningpercent"
export const QUERY_COUNT_UNIQUE_QUERIES = "countuniquequeries"
export const QUERY_GENERAL_STATS = "generalstats"
export const QUERY_TOP5_PAGE_HITS = "pageHits"