services:
  backend:
    container_name: query-analyzer-api-cnt
    image: hlinneo4j2/hlin-neo4j:latest-api-amd64
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8000:8000"
    volumes:
      - ./databases:/databases

  ui:
    container_name: query-analyzer-ui-cnt
    image: hlinneo4j2/hlin-neo4j:latest-ui-amd64
    build:
      context: ./ui
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "5173:5173"