services:
  # backend:
  #   container_name: query-analyzer-api-cnt
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./databases:/databases

  ui:
    container_name: query-analyzer-ui-cnt
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    network_mode: host
    # volumes:
    #   - ./ui:/app
    # environment:
    #   - API_URL=http://localhost:8000/api