services:
  flask:
    container_name: query-analyzer-apiflask-cnt
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./databases:/databases

  ui:
    container_name: query-analyzer-ui-cnt
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"