name: GitHub Actions Demo - ssh test
run-name: ${{ github.actor }} testing ssh
on: [push]
jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.gcp_credentials }}'
